sudo: false

language: cpp

matrix:
  fast_finish: true
  include:
    - env: NODE_VERSION=4.0 TEST_SCRIPT=lint
      os: linux

    - env: NODE_VERSION=lts/argon TEST_SCRIPT=test
      os: linux
      addons: &buildpackages
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - libcurl4-openssl-dev
          - uuid-dev
          - g++-4.8

    - env: NODE_VERSION=lts/boron TEST_SCRIPT=test
      os: linux
      addons: *buildpackages

    - env: NODE_VERSION=stable TEST_SCRIPT=test
      os: linux
      addons: *buildpackages

    - env: NODE_VERSION=7 TEST_SCRIPT=test
      os: linux
      addons: *buildpackages

    - env: NODE_VERSION=lts/boron TEST_SCRIPT=test
      os: osx
      osx_image: xcode8.2

    - env: NODE_VERSION=stable TEST_SCRIPT=test
      os: osx
      osx_image: xcode8.2

    - env: NODE_VERSION=7 TEST_SCRIPT=test
      os: osx
      osx_image: xcode8.2

    # Allowed failures must be specified twice - once in "include" to have them
    # run, and again in "allow_failures" to not have them break the build.
    # Below are the allowed failures:

    - env: NODE_VERSION=stable TEST_SCRIPT=publish-coverage
      os: linux
      addons: *buildpackages

  allow_failures:
    - env: NODE_VERSION=stable TEST_SCRIPT=publish-coverage
      os: linux
      addons: *buildpackages

install:
- >
  if test "x${TRAVIS_OS_NAME}x" = "xlinuxx"; then
    export CXX="g++-4.8" CC="gcc-4.8"
  fi
- rm -rf ~/.nvm
- wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.7/install.sh | bash
- source ~/.nvm/nvm.sh
- nvm install "${NODE_VERSION}"
- npm install -g npm@^2.14.2
- >
  if test "x${TRAVIS_OS_NAME}x" = "xosxx"; then
    brew install scons
  fi
- node --version
- npm --version
- npm install -g grunt-cli

script:
- >
  if test "x${TEST_SCRIPT}x" = "xtestx" -o "x${TEST_SCRIPT}x" = "xpublish-coveragex"; then
    npm install -g "$(npm pack)"
    npm link iotivity-node
  fi
- npm install --ignore-scripts
- grunt "${TEST_SCRIPT}" --ci

notifications:
  irc:
    channels:
      - "chat.freenode.net#iotivity-node"
