sudo: false
language: cpp

matrix:
  fast_finish: true
  include:
  - env: NODE_VERSION=8.4.0 TEST_SCRIPT=test NODE_OPTIONS=--napi-modules
    os: linux
    addons: &1
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libcurl4-openssl-dev
        - uuid-dev
        - g++-4.8
        - libboost-all-dev
install:
- |
  if test "x${TRAVIS_OS_NAME}x" = "xlinuxx"; then
    export CXX="g++-4.8" CC="gcc-4.8"
  fi
- rm -rf ~/.nvm
- wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.7/install.sh |
  bash
- source ~/.nvm/nvm.sh
- nvm install "${NODE_VERSION}"
- |
  if test "x${TRAVIS_OS_NAME}x" = "xosxx"; then
    sudo easy_install pip
    sudo pip install --egg 'scons<3.0.0'
  fi
- node --version
- npm --version
- npm install -g grunt-cli
- |
  if test "x${TEST_SCRIPT}x" = "xtestx" -o "x${TEST_SCRIPT}x" = "xpublish-coveragex"; then
    npm install -g "$(npm pack)"
  fi
- npm install --ignore-scripts
- |
  if test "x${TEST_SCRIPT}x" = "xtestx" -o "x${TEST_SCRIPT}x" = "xpublish-coveragex"; then
    npm link iotivity-node
  fi
script:
- NODE_OPTIONS="${NODE_OPTIONS}" grunt "${TEST_SCRIPT}" --ci

# Send a notification to chat.freenode.net#iotivity-node
# The server#channel-name is encrypted so notifications are only sent from the
# main repo and not from forks or PRs.
notifications:
  irc:
    channels:
    - secure: i1PXMQry2x9WqT2Iv9Lq66+VHkettjrDhiC1C6ha/yPI5P9sNGZmad0hiBtg7Z8NfmaFuWUqwFI5fnw/iM1hqQKMQVIuYLsLdagZLldtYcUR3Un+2yVsn9PFj5PnS2kd9aUBOO+7YOt1v6snRGGJQsjlD5cAKaZ7QZrw2OpMVsjLmS1TjrOZz6jPkZUqixVo+lnnWTKIWjx7LIkaCiihPUn1CDV5ke3s9BLp/9NhCe77wa2qq1AXIjrjUYPif9kogqnIKJW/KTqvgcixOTxJqjNIC/dKWU8UEyH3ZeH9JxeSrZwxztTOHCgfcDklanZrI9uCUOMOa1Vs/MxW8FLxr09SsjYWH4GYjQpb5RRzHvRLYlL1VukdUz1M5nr0riImrDDumigxxGNpmgLprQ9w1jkMK1AnDtAhA8CBkad+D0gkuwRej53izi285zPu9MV/DTSW1zGmYo33GoyV3pbkuItdCEERmC7aoY4cRTLjjdOL8dJUjpZ8R7mGJRZWEtDl629eSbDhciA8LM9SCiXLrT73wiHtSO/fE/BPJy2QBOQfbtEx7HCQ3yNyPFmvkE/cZts0dtF5WAOhw6xSDXuNKq+rdk3bv133GOoqoTZ7rs1R11fKPOZG6MKDyyGrSHB3vG6u1L+9blq9CYTvfncka/u7HVh9RV1cuzCuYfY7yog=
