init:
  - git config --global core.autocrlf input

shallow_clone: true

environment:
  matrix:
    - nodejs_version: "6.9.1"
    - nodejs_version: "7.0.0"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version x64
  - pip install --egg scons

test_script:
  - npm install -g grunt-cli
  - ps: npm install -g "$(npm pack)"
  - npm install --ignore-scripts
  - npm link iotivity-node
  - grunt test --ci

build: off
